import type { DifficultyLevel, WorkoutCategory, WorkoutTemplate } from '../types/templates.js';

/** Curated gym workout templates for cyclists */
export const GYM_TEMPLATES: readonly WorkoutTemplate[] = [
  {
    id: 'cycling-lower-body',
    name: 'Cycling Lower Body Strength',
    description: 'Lower body strength exercises targeting muscles most used in cycling',
    category: 'strength',
    difficulty: 'intermediate',
    estimatedDurationMinutes: 45,
    estimatedTss: 40,
    exercises: [
      {
        name: 'Barbell Back Squat',
        sets: 4,
        reps: '8-10',
        restSeconds: 90,
        notes: 'Focus on full depth and controlled eccentric',
        targetMuscles: ['quadriceps', 'glutes'],
      },
      {
        name: 'Romanian Deadlift',
        sets: 3,
        reps: '10-12',
        restSeconds: 90,
        notes: 'Hinge at hips, keep back neutral',
        targetMuscles: ['hamstrings', 'glutes', 'lower_back'],
      },
      {
        name: 'Bulgarian Split Squat',
        sets: 3,
        reps: 10,
        restSeconds: 60,
        notes: 'Per leg. Rear foot elevated on bench',
        targetMuscles: ['quadriceps', 'glutes'],
      },
      {
        name: 'Single-Leg Press',
        sets: 3,
        reps: 12,
        restSeconds: 60,
        notes: 'Per leg. Moderate weight, controlled movement',
        targetMuscles: ['quadriceps', 'glutes', 'hamstrings'],
      },
      {
        name: 'Standing Calf Raise',
        sets: 3,
        reps: 15,
        restSeconds: 45,
        notes: 'Full range of motion with pause at top',
        targetMuscles: ['calves'],
      },
    ],
    targetMuscles: ['quadriceps', 'hamstrings', 'glutes', 'calves', 'lower_back'],
    tags: ['cycling', 'lower-body', 'strength', 'intermediate'],
  },
  {
    id: 'core-stability',
    name: 'Core Stability for Endurance Athletes',
    description: 'Core-focused workout to improve stability and power transfer on the bike',
    category: 'core',
    difficulty: 'beginner',
    estimatedDurationMinutes: 30,
    estimatedTss: 20,
    exercises: [
      {
        name: 'Plank',
        sets: 3,
        reps: '45s',
        restSeconds: 30,
        notes: 'Maintain neutral spine throughout',
        targetMuscles: ['core'],
      },
      {
        name: 'Side Plank',
        sets: 2,
        reps: '30s',
        restSeconds: 30,
        notes: 'Per side. Stack hips vertically',
        targetMuscles: ['core'],
      },
      {
        name: 'Dead Bug',
        sets: 3,
        reps: 10,
        restSeconds: 30,
        notes: 'Per side. Keep lower back pressed to floor',
        targetMuscles: ['core', 'hip_flexors'],
      },
      {
        name: 'Bird Dog',
        sets: 3,
        reps: 10,
        restSeconds: 30,
        notes: 'Per side. Extend opposite arm and leg',
        targetMuscles: ['core', 'lower_back'],
      },
      {
        name: 'Pallof Press',
        sets: 3,
        reps: 10,
        restSeconds: 30,
        notes: 'Per side. Resist rotation with cable or band',
        targetMuscles: ['core'],
      },
      {
        name: 'Hollow Hold',
        sets: 3,
        reps: '30s',
        restSeconds: 30,
        notes: 'Press lower back into floor, legs extended',
        targetMuscles: ['core', 'hip_flexors'],
      },
    ],
    targetMuscles: ['core', 'lower_back', 'hip_flexors'],
    tags: ['cycling', 'core', 'stability', 'beginner'],
  },
  {
    id: 'injury-prevention',
    name: 'Injury Prevention & Prehab',
    description: 'Mobility and prehab exercises to prevent common cycling injuries',
    category: 'mobility',
    difficulty: 'beginner',
    estimatedDurationMinutes: 25,
    estimatedTss: 15,
    exercises: [
      {
        name: 'Single-Leg Balance',
        sets: 3,
        reps: '30s',
        restSeconds: 15,
        notes: 'Per leg. Eyes open, progress to eyes closed',
        targetMuscles: ['calves', 'glutes'],
      },
      {
        name: 'Clamshell',
        sets: 3,
        reps: 15,
        restSeconds: 30,
        notes: 'Per side. Keep feet together, open knees',
        targetMuscles: ['glutes', 'hip_flexors'],
      },
      {
        name: 'IT Band Foam Roll',
        sets: 2,
        reps: '45s',
        restSeconds: 15,
        notes: 'Per side. Roll slowly from hip to knee',
        targetMuscles: ['quadriceps', 'hamstrings'],
      },
      {
        name: 'Hip Flexor Stretch',
        sets: 2,
        reps: '45s',
        restSeconds: 15,
        notes: 'Per side. Half-kneeling position, squeeze glute',
        targetMuscles: ['hip_flexors', 'glutes'],
      },
      {
        name: 'Ankle Mobility Circle',
        sets: 2,
        reps: 10,
        restSeconds: 15,
        notes: 'Per ankle. Slow controlled circles in each direction',
        targetMuscles: ['calves'],
      },
    ],
    targetMuscles: ['hip_flexors', 'glutes', 'hamstrings', 'calves', 'quadriceps'],
    tags: ['cycling', 'prehab', 'mobility', 'beginner'],
  },
  {
    id: 'upper-body-balance',
    name: 'Upper Body Posture Balance',
    description: 'Upper body exercises to counteract cycling posture and improve balance',
    category: 'strength',
    difficulty: 'intermediate',
    estimatedDurationMinutes: 35,
    estimatedTss: 30,
    exercises: [
      {
        name: 'Dumbbell Bent-Over Row',
        sets: 3,
        reps: 12,
        restSeconds: 60,
        notes: 'Squeeze shoulder blades together at top',
        targetMuscles: ['upper_back', 'arms'],
      },
      {
        name: 'Reverse Fly',
        sets: 3,
        reps: 12,
        restSeconds: 45,
        notes: 'Light weight, focus on squeezing rear delts',
        targetMuscles: ['upper_back', 'shoulders'],
      },
      {
        name: 'Face Pull',
        sets: 3,
        reps: 15,
        restSeconds: 45,
        notes: 'Cable or band. Pull to forehead, externally rotate',
        targetMuscles: ['upper_back', 'shoulders'],
      },
      {
        name: 'Push-Up',
        sets: 3,
        reps: 12,
        restSeconds: 60,
        notes: 'Full range of motion, maintain plank position',
        targetMuscles: ['chest', 'shoulders', 'arms'],
      },
      {
        name: 'Shoulder External Rotation',
        sets: 3,
        reps: 12,
        restSeconds: 30,
        notes: 'Per side. Light band or cable, elbow at 90 degrees',
        targetMuscles: ['shoulders'],
      },
    ],
    targetMuscles: ['upper_back', 'shoulders', 'chest', 'arms'],
    tags: ['cycling', 'upper-body', 'posture', 'intermediate'],
  },
  {
    id: 'explosive-power',
    name: 'Explosive Power Development',
    description: 'Plyometric exercises for sprint power and climbing acceleration',
    category: 'plyometric',
    difficulty: 'advanced',
    estimatedDurationMinutes: 40,
    estimatedTss: 50,
    exercises: [
      {
        name: 'Box Jump',
        sets: 4,
        reps: 6,
        restSeconds: 120,
        notes: 'Step down between reps. Focus on explosive hip extension',
        targetMuscles: ['quadriceps', 'glutes', 'calves'],
      },
      {
        name: 'Jump Squat',
        sets: 3,
        reps: 8,
        restSeconds: 90,
        notes: 'Bodyweight or light load. Land softly',
        targetMuscles: ['quadriceps', 'glutes'],
      },
      {
        name: 'Alternating Lunge Jump',
        sets: 3,
        reps: 8,
        restSeconds: 90,
        notes: 'Per side. Explode upward, switch legs mid-air',
        targetMuscles: ['quadriceps', 'glutes', 'hamstrings'],
      },
      {
        name: 'Kettlebell Swing',
        sets: 4,
        reps: 12,
        restSeconds: 60,
        notes: 'Hip hinge movement, drive hips forward explosively',
        targetMuscles: ['glutes', 'hamstrings', 'core'],
      },
      {
        name: 'Power Clean',
        sets: 4,
        reps: 5,
        restSeconds: 120,
        notes: 'Moderate weight. Full triple extension',
        targetMuscles: ['quadriceps', 'glutes', 'hamstrings', 'calves'],
      },
    ],
    targetMuscles: ['quadriceps', 'glutes', 'hamstrings', 'calves', 'core'],
    tags: ['cycling', 'power', 'plyometric', 'advanced'],
  },
  {
    id: 'full-body-maintenance',
    name: 'Full-Body Maintenance',
    description: 'Light full-body session for taper weeks or recovery periods',
    category: 'strength',
    difficulty: 'beginner',
    estimatedDurationMinutes: 30,
    estimatedTss: 25,
    exercises: [
      {
        name: 'Goblet Squat',
        sets: 3,
        reps: 12,
        restSeconds: 60,
        notes: 'Light to moderate weight, focus on form',
        targetMuscles: ['quadriceps', 'glutes'],
      },
      {
        name: 'Push-Up',
        sets: 3,
        reps: 10,
        restSeconds: 45,
        notes: 'Modify on knees if needed',
        targetMuscles: ['chest', 'shoulders', 'arms'],
      },
      {
        name: 'TRX Row',
        sets: 3,
        reps: 12,
        restSeconds: 45,
        notes: 'Adjust body angle for difficulty',
        targetMuscles: ['upper_back', 'arms'],
      },
      {
        name: 'Glute Bridge',
        sets: 3,
        reps: 15,
        restSeconds: 30,
        notes: 'Squeeze glutes at top, hold 2 seconds',
        targetMuscles: ['glutes', 'hamstrings'],
      },
      {
        name: 'Plank',
        sets: 3,
        reps: '30s',
        restSeconds: 30,
        notes: 'Maintain neutral spine',
        targetMuscles: ['core'],
      },
    ],
    targetMuscles: [
      'quadriceps',
      'glutes',
      'core',
      'upper_back',
      'chest',
      'shoulders',
      'arms',
      'hamstrings',
    ],
    tags: ['cycling', 'maintenance', 'full-body', 'beginner'],
  },
] as const;

/** Look up a gym template by its unique ID */
export function getGymTemplateById(id: string): WorkoutTemplate | undefined {
  return GYM_TEMPLATES.find((t) => t.id === id);
}

/** Get all gym templates matching a workout category */
export function getGymTemplatesByCategory(category: WorkoutCategory): WorkoutTemplate[] {
  return GYM_TEMPLATES.filter((t) => t.category === category);
}

/** Get all gym templates matching a difficulty level */
export function getGymTemplatesByDifficulty(difficulty: DifficultyLevel): WorkoutTemplate[] {
  return GYM_TEMPLATES.filter((t) => t.difficulty === difficulty);
}
