import type { DifficultyLevel, WorkoutCategory, WorkoutTemplate } from '../types/templates.js';

/** Curated travel workout templates for cyclists without gym access */
export const TRAVEL_TEMPLATES: readonly WorkoutTemplate[] = [
  {
    id: 'hotel-room-circuit',
    name: 'Hotel Room Circuit',
    description:
      'Bodyweight-only circuit for small spaces — ideal when traveling with no equipment',
    category: 'core',
    difficulty: 'beginner',
    estimatedDurationMinutes: 20,
    estimatedTss: 15,
    exercises: [
      {
        name: 'Push-Up',
        sets: 3,
        reps: 12,
        restSeconds: 30,
        notes: 'Full range of motion, modify on knees if needed',
        targetMuscles: ['chest', 'shoulders', 'arms'],
      },
      {
        name: 'Bodyweight Squat',
        sets: 3,
        reps: 15,
        restSeconds: 30,
        notes: 'Sit back into heels, chest up',
        targetMuscles: ['quadriceps', 'glutes'],
      },
      {
        name: 'Plank',
        sets: 3,
        reps: '30s',
        restSeconds: 20,
        notes: 'Maintain neutral spine, squeeze glutes',
        targetMuscles: ['core'],
      },
      {
        name: 'Mountain Climber',
        sets: 3,
        reps: '30s',
        restSeconds: 30,
        notes: 'Controlled pace, drive knees toward chest',
        targetMuscles: ['core', 'hip_flexors', 'shoulders'],
      },
      {
        name: 'Alternating Reverse Lunge',
        sets: 3,
        reps: 10,
        restSeconds: 30,
        notes: 'Per side. Step back, lower knee toward floor',
        targetMuscles: ['quadriceps', 'glutes', 'hamstrings'],
      },
      {
        name: 'Glute Bridge',
        sets: 3,
        reps: 15,
        restSeconds: 20,
        notes: 'Squeeze glutes at top, hold 2 seconds',
        targetMuscles: ['glutes', 'hamstrings'],
      },
    ],
    targetMuscles: [
      'chest',
      'shoulders',
      'arms',
      'quadriceps',
      'glutes',
      'core',
      'hip_flexors',
      'hamstrings',
    ],
    tags: ['cycling', 'travel', 'bodyweight', 'hotel', 'beginner'],
  },
  {
    id: 'park-strength',
    name: 'Park Strength Session',
    description:
      'Outdoor strength workout using benches, bars, and open space for traveling cyclists',
    category: 'strength',
    difficulty: 'intermediate',
    estimatedDurationMinutes: 35,
    estimatedTss: 30,
    exercises: [
      {
        name: 'Bench Step-Up',
        sets: 3,
        reps: 10,
        restSeconds: 60,
        notes: 'Per leg. Drive through heel, full hip extension at top',
        targetMuscles: ['quadriceps', 'glutes'],
      },
      {
        name: 'Bench Dip',
        sets: 3,
        reps: 12,
        restSeconds: 45,
        notes: 'Hands on bench edge, lower until elbows at 90 degrees',
        targetMuscles: ['arms', 'shoulders', 'chest'],
      },
      {
        name: 'Pull-Up',
        sets: 3,
        reps: '6-8',
        restSeconds: 90,
        notes: 'Use bar if available; substitute inverted row on low bar',
        targetMuscles: ['upper_back', 'arms'],
      },
      {
        name: 'Pistol Squat Progression',
        sets: 3,
        reps: 6,
        restSeconds: 60,
        notes: 'Per leg. Hold bench for balance if needed',
        targetMuscles: ['quadriceps', 'glutes', 'calves'],
      },
      {
        name: 'Decline Push-Up',
        sets: 3,
        reps: 10,
        restSeconds: 45,
        notes: 'Feet elevated on bench for added difficulty',
        targetMuscles: ['chest', 'shoulders', 'arms'],
      },
    ],
    targetMuscles: ['quadriceps', 'glutes', 'calves', 'arms', 'shoulders', 'chest', 'upper_back'],
    tags: ['cycling', 'travel', 'outdoor', 'park', 'intermediate'],
  },
  {
    id: 'band-resistance-travel',
    name: 'Resistance Band Travel Workout',
    description: 'Full-body strength session using only a packable resistance band',
    category: 'strength',
    difficulty: 'intermediate',
    estimatedDurationMinutes: 30,
    estimatedTss: 25,
    exercises: [
      {
        name: 'Band Squat',
        sets: 3,
        reps: 15,
        restSeconds: 45,
        notes: 'Stand on band, hold handles at shoulders',
        targetMuscles: ['quadriceps', 'glutes'],
      },
      {
        name: 'Band Pull-Apart',
        sets: 3,
        reps: 15,
        restSeconds: 30,
        notes: 'Arms extended, pull band apart at chest height',
        targetMuscles: ['upper_back', 'shoulders'],
      },
      {
        name: 'Band Deadlift',
        sets: 3,
        reps: 12,
        restSeconds: 45,
        notes: 'Stand on band, hinge at hips, keep back neutral',
        targetMuscles: ['hamstrings', 'glutes', 'lower_back'],
      },
      {
        name: 'Band Lateral Walk',
        sets: 3,
        reps: 10,
        restSeconds: 30,
        notes: 'Per direction. Band around ankles, stay low',
        targetMuscles: ['glutes', 'hip_flexors'],
      },
      {
        name: 'Band Row',
        sets: 3,
        reps: 12,
        restSeconds: 45,
        notes: 'Seated, band around feet, pull to torso',
        targetMuscles: ['upper_back', 'arms'],
      },
    ],
    targetMuscles: [
      'quadriceps',
      'glutes',
      'upper_back',
      'shoulders',
      'hamstrings',
      'lower_back',
      'hip_flexors',
      'arms',
    ],
    tags: ['cycling', 'travel', 'resistance-band', 'intermediate'],
  },
  {
    id: 'airport-mobility',
    name: 'Airport Mobility Routine',
    description: 'Quick standing mobility routine for long travel days — no mat needed',
    category: 'mobility',
    difficulty: 'beginner',
    estimatedDurationMinutes: 15,
    estimatedTss: 10,
    exercises: [
      {
        name: 'Standing Quad Stretch',
        sets: 2,
        reps: '30s',
        restSeconds: 10,
        notes: 'Per leg. Hold wall for balance if needed',
        targetMuscles: ['quadriceps', 'hip_flexors'],
      },
      {
        name: 'Hip Circle',
        sets: 2,
        reps: 10,
        restSeconds: 10,
        notes: 'Per direction. Large controlled circles',
        targetMuscles: ['hip_flexors', 'glutes'],
      },
      {
        name: 'Ankle Circle',
        sets: 2,
        reps: 10,
        restSeconds: 10,
        notes: 'Per ankle. Slow circles in each direction',
        targetMuscles: ['calves'],
      },
      {
        name: 'Thoracic Rotation',
        sets: 2,
        reps: 8,
        restSeconds: 10,
        notes: 'Per side. Hand behind head, rotate upper body',
        targetMuscles: ['upper_back', 'core'],
      },
      {
        name: 'Standing Neck Stretch',
        sets: 2,
        reps: '20s',
        restSeconds: 10,
        notes: 'Per side. Gently tilt ear toward shoulder',
        targetMuscles: ['shoulders'],
      },
    ],
    targetMuscles: [
      'quadriceps',
      'hip_flexors',
      'glutes',
      'calves',
      'upper_back',
      'core',
      'shoulders',
    ],
    tags: ['cycling', 'travel', 'mobility', 'airport', 'beginner'],
  },
  {
    id: 'bodyweight-hiit',
    name: 'Bodyweight HIIT',
    description: 'High-intensity bodyweight intervals for maintaining fitness on the road',
    category: 'plyometric',
    difficulty: 'advanced',
    estimatedDurationMinutes: 25,
    estimatedTss: 40,
    exercises: [
      {
        name: 'Burpee',
        sets: 4,
        reps: 8,
        restSeconds: 45,
        notes: 'Full range — squat thrust with push-up and jump',
        targetMuscles: ['quadriceps', 'glutes', 'chest', 'shoulders'],
      },
      {
        name: 'Jump Squat',
        sets: 4,
        reps: 10,
        restSeconds: 45,
        notes: 'Land softly, absorb through knees',
        targetMuscles: ['quadriceps', 'glutes', 'calves'],
      },
      {
        name: 'High Knees',
        sets: 3,
        reps: '30s',
        restSeconds: 30,
        notes: 'Drive knees above hip height, pump arms',
        targetMuscles: ['hip_flexors', 'core', 'calves'],
      },
      {
        name: 'Push-Up to T-Rotation',
        sets: 3,
        reps: 8,
        restSeconds: 45,
        notes: 'Per side. Push-up, then rotate into side plank with arm extended',
        targetMuscles: ['chest', 'shoulders', 'core'],
      },
      {
        name: 'Tuck Jump',
        sets: 3,
        reps: 8,
        restSeconds: 60,
        notes: 'Explode upward, tuck knees to chest mid-air',
        targetMuscles: ['quadriceps', 'glutes', 'calves', 'core'],
      },
    ],
    targetMuscles: ['quadriceps', 'glutes', 'chest', 'shoulders', 'calves', 'hip_flexors', 'core'],
    tags: ['cycling', 'travel', 'hiit', 'bodyweight', 'advanced'],
  },
  {
    id: 'yoga-for-cyclists',
    name: 'Yoga for Cyclists',
    description:
      'Yoga-inspired flexibility routine targeting common cycling tightness — hips, hamstrings, and back',
    category: 'mobility',
    difficulty: 'beginner',
    estimatedDurationMinutes: 30,
    estimatedTss: 10,
    exercises: [
      {
        name: 'Downward Dog',
        sets: 3,
        reps: '30s',
        restSeconds: 15,
        notes: 'Press heels toward floor, lengthen spine',
        targetMuscles: ['hamstrings', 'calves', 'shoulders'],
      },
      {
        name: 'Pigeon Pose',
        sets: 2,
        reps: '45s',
        restSeconds: 15,
        notes: 'Per side. Front shin parallel to mat if possible',
        targetMuscles: ['glutes', 'hip_flexors'],
      },
      {
        name: 'Figure-4 Stretch',
        sets: 2,
        reps: '30s',
        restSeconds: 15,
        notes: 'Per side. Supine, ankle on opposite knee, pull thigh toward chest',
        targetMuscles: ['glutes', 'hip_flexors'],
      },
      {
        name: 'Cat-Cow',
        sets: 3,
        reps: 8,
        restSeconds: 10,
        notes: 'Alternate between arching and rounding the spine',
        targetMuscles: ['core', 'lower_back'],
      },
      {
        name: "Child's Pose",
        sets: 2,
        reps: '30s',
        restSeconds: 10,
        notes: 'Knees wide, arms extended forward, breathe deeply',
        targetMuscles: ['lower_back', 'shoulders'],
      },
      {
        name: 'Thread the Needle',
        sets: 2,
        reps: '30s',
        restSeconds: 15,
        notes: 'Per side. From tabletop, reach arm under body and rotate',
        targetMuscles: ['upper_back', 'shoulders'],
      },
    ],
    targetMuscles: [
      'hamstrings',
      'calves',
      'shoulders',
      'glutes',
      'hip_flexors',
      'core',
      'lower_back',
      'upper_back',
    ],
    tags: ['cycling', 'travel', 'yoga', 'flexibility', 'beginner'],
  },
] as const;

/** Look up a travel template by its unique ID */
export function getTravelTemplateById(id: string): WorkoutTemplate | undefined {
  return TRAVEL_TEMPLATES.find((t) => t.id === id);
}

/** Get all travel templates matching a workout category */
export function getTravelTemplatesByCategory(category: WorkoutCategory): WorkoutTemplate[] {
  return TRAVEL_TEMPLATES.filter((t) => t.category === category);
}

/** Get all travel templates matching a difficulty level */
export function getTravelTemplatesByDifficulty(difficulty: DifficultyLevel): WorkoutTemplate[] {
  return TRAVEL_TEMPLATES.filter((t) => t.difficulty === difficulty);
}
